#!/bin/sh /etc/rc.common 

START=93

USE_PROCD=1
PROG=/usr/sbin/redis-server
CONFIGFILE=/etc/config/redis.conf

start_service() {
	include /lib/functions
	procd_open_instance
	procd_set_param command $PROG $CONFIGFILE 
	procd_set_param file $CONFIGFILE
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	echo "restart"
}

stop_service() {
	echo "stop"
}
