#!/bin/sh /etc/rc.common 

START=99

USE_PROCD=1
PROG=/ugw/script/essential.sh 

start_service() {
	include /lib/functions
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	echo "restart essential"
	killstr essential/main.lua
}

stop_service() {
	echo "stop essential"
	killstr essential/main.lua
}
