#!/bin/sh /etc/rc.common 

START=93

USE_PROCD=1
PROG=/ugw/script/websrv.sh 

start_service() {
	include /lib/functions
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	echo "restart websrv"
}

stop_service() {
	echo "stop websrv"
}
