#!/bin/sh /etc/rc.common 

START=94

USE_PROCD=1
PROG=/ugw/script/userauth.sh 

start_service() {
	include /lib/functions
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	echo "restart userauth"
	killstr userauth/main.lua
}

stop_service() {
	echo "stop userauth" 
	killstr userauth/main.lua
}
